[0m10:34:42.765785 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e1c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108edc070>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108edff40>]}


============================== 10:34:42.769961 | a852c7ab-a41a-47f0-b710-cfbcbfc8cb2d ==============================
[0m10:34:42.769961 [info ] [MainThread]: Running with dbt=1.8.8
[0m10:34:42.770515 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/abdeltouati/.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init wild_dbt_project', 'send_anonymous_usage_stats': 'True'}
[0m10:34:42.781964 [debug] [MainThread]: Starter project path: /opt/homebrew/lib/python3.10/site-packages/dbt/include/starter_project
[0m10:34:42.787531 [info ] [MainThread]: 
Your new dbt project "wild_dbt_project" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m10:34:42.787865 [info ] [MainThread]: Setting up your profile.
[0m10:34:42.794325 [error] [MainThread]: Encountered an error:

[0m10:34:42.796240 [error] [MainThread]: Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/requires.py", line 138, in wrapper
    result, success = func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/requires.py", line 101, in wrapper
    return func(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/cli/main.py", line 470, in init
    results = task.run()
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/task/init.py", line 347, in run
    self.setup_profile(profile_name)
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/task/init.py", line 262, in setup_profile
    adapter = self.ask_for_adapter_choice()
  File "/opt/homebrew/lib/python3.10/site-packages/dbt/task/init.py", line 243, in ask_for_adapter_choice
    numeric_choice = click.prompt(prompt_msg, type=click.INT)
  File "/opt/homebrew/lib/python3.10/site-packages/click/termui.py", line 164, in prompt
    value = prompt_func(prompt)
  File "/opt/homebrew/lib/python3.10/site-packages/click/termui.py", line 147, in prompt_func
    raise Abort() from None
click.exceptions.Abort

[0m10:34:42.797796 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1074e1c90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108ede740>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x108c037f0>]}
[0m10:34:42.798170 [debug] [MainThread]: Flushing usage events
[0m10:34:43.240970 [debug] [MainThread]: An error was encountered while trying to flush usage events
